export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#858382",
        "background": "#fbf9f5",
        "surface-container": "#efeeea",
        "primary-fixed-dim": "#c9c6c4",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "outline-variant": "#c7c7c0",
        "on-secondary-fixed-variant": "#842500",
        "surface-variant": "#e4e2de",
        "secondary-container": "#fe6f3f",
        "on-background": "#1b1c1a",
        "on-tertiary-fixed-variant": "#832600",
        "error-container": "#ffdad6",
        "tertiary-container": "#390c00",
        "surface-container-highest": "#e4e2de",
        "primary-fixed": "#e5e2e0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-primary-fixed-variant": "#474745",
        "surface-container-low": "#f5f3ef",
        "on-error-container": "#93000a",
        "surface": "#fbf9f5",
        "on-secondary-fixed": "#3a0b00",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ffb59e",
        "tertiary-fixed": "#ffdbd0",
        "on-secondary-container": "#621900",
        "secondary-fixed": "#ffdbd0",
        "on-surface": "#1b1c1a",
        "surface-dim": "#dbdad6",
        "surface-tint": "#5f5e5d",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#1c1c1a",
        "inverse-primary": "#c9c6c4",
        "surface-container-lowest": "#ffffff",
        "secondary": "#ac3505",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f0ed",
        "primary-container": "#1c1c1a",
        "outline": "#767872",
        "tertiary": "#000000",
        "on-tertiary-fixed": "#390c00",
        "on-surface-variant": "#464742",
        "surface-container-high": "#eae8e4",
        "on-tertiary-container": "#e25621",
        "primary": "#000000",
        "surface-bright": "#fbf9f5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-2xl": "3rem",
        "space-4xl": "6rem",
        "space-3xs": "0.125rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "gutter-desktop": "3rem",
        "space-sm": "0.75rem",
        "space-3xl": "4rem",
        "space-2xs": "0.25rem",
        "space-xl": "2rem",
        "max-width-content": "80rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1.25rem",
        "space-5xl": "8rem",
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans"],
        "label-badge": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-code": ["JetBrains Mono"],
        "meta-date": ["JetBrains Mono"],
        "body-lead": ["Plus Jakarta Sans"],
        "headline-lg": ["Syne"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Syne"],
        "headline-xl": ["Syne"],
        "headline-sm": ["Plus Jakarta Sans"],
        "display-hero": ["Syne"],
        "display-hero-mobile": ["Syne"],
      },
      fontSize: {
        "body-sm": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-badge": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "1.875rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-code": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "500" }],
        "meta-date": ["0.8125rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-lead": ["1.25rem", { lineHeight: "1.875rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["2rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["1rem", { lineHeight: "1.625rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl-mobile": ["2rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["3rem", { lineHeight: "3.25rem", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["4.5rem", { lineHeight: "4.75rem", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-hero-mobile": ["2.75rem", { lineHeight: "3rem", letterSpacing: "-0.03em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
